/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: cloud.proto */

#ifndef PROTOBUF_C_cloud_2eproto__INCLUDED
#define PROTOBUF_C_cloud_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Cloud__CmdGetSetDetails Cloud__CmdGetSetDetails;
typedef struct _Cloud__RespGetSetDetails Cloud__RespGetSetDetails;
typedef struct _Cloud__CloudConfigPayload Cloud__CloudConfigPayload;


/* --- enums --- */

typedef enum _Cloud__CloudConfigStatus {
  CLOUD__CLOUD_CONFIG_STATUS__Success = 0,
  CLOUD__CLOUD_CONFIG_STATUS__InvalidParam = 1,
  CLOUD__CLOUD_CONFIG_STATUS__InvalidState = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CLOUD__CLOUD_CONFIG_STATUS)
} Cloud__CloudConfigStatus;
typedef enum _Cloud__CloudConfigMsgType {
  CLOUD__CLOUD_CONFIG_MSG_TYPE__TypeCmdGetSetDetails = 0,
  CLOUD__CLOUD_CONFIG_MSG_TYPE__TypeRespGetSetDetails = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CLOUD__CLOUD_CONFIG_MSG_TYPE)
} Cloud__CloudConfigMsgType;

/* --- messages --- */

struct  _Cloud__CmdGetSetDetails
{
  ProtobufCMessage base;
  char *userid;
  char *secretkey;
};
#define CLOUD__CMD_GET_SET_DETAILS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cloud__cmd_get_set_details__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _Cloud__RespGetSetDetails
{
  ProtobufCMessage base;
  Cloud__CloudConfigStatus status;
  char *devicesecret;
};
#define CLOUD__RESP_GET_SET_DETAILS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cloud__resp_get_set_details__descriptor) \
    , CLOUD__CLOUD_CONFIG_STATUS__Success, (char *)protobuf_c_empty_string }


typedef enum {
  CLOUD__CLOUD_CONFIG_PAYLOAD__PAYLOAD__NOT_SET = 0,
  CLOUD__CLOUD_CONFIG_PAYLOAD__PAYLOAD_CMD_GET_SET_DETAILS = 10,
  CLOUD__CLOUD_CONFIG_PAYLOAD__PAYLOAD_RESP_GET_SET_DETAILS = 11
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CLOUD__CLOUD_CONFIG_PAYLOAD__PAYLOAD)
} Cloud__CloudConfigPayload__PayloadCase;

struct  _Cloud__CloudConfigPayload
{
  ProtobufCMessage base;
  Cloud__CloudConfigMsgType msg;
  Cloud__CloudConfigPayload__PayloadCase payload_case;
  union {
    Cloud__CmdGetSetDetails *cmd_get_set_details;
    Cloud__RespGetSetDetails *resp_get_set_details;
  };
};
#define CLOUD__CLOUD_CONFIG_PAYLOAD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cloud__cloud_config_payload__descriptor) \
    , CLOUD__CLOUD_CONFIG_MSG_TYPE__TypeCmdGetSetDetails, CLOUD__CLOUD_CONFIG_PAYLOAD__PAYLOAD__NOT_SET, {0} }


/* Cloud__CmdGetSetDetails methods */
void   cloud__cmd_get_set_details__init
                     (Cloud__CmdGetSetDetails         *message);
size_t cloud__cmd_get_set_details__get_packed_size
                     (const Cloud__CmdGetSetDetails   *message);
size_t cloud__cmd_get_set_details__pack
                     (const Cloud__CmdGetSetDetails   *message,
                      uint8_t             *out);
size_t cloud__cmd_get_set_details__pack_to_buffer
                     (const Cloud__CmdGetSetDetails   *message,
                      ProtobufCBuffer     *buffer);
Cloud__CmdGetSetDetails *
       cloud__cmd_get_set_details__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cloud__cmd_get_set_details__free_unpacked
                     (Cloud__CmdGetSetDetails *message,
                      ProtobufCAllocator *allocator);
/* Cloud__RespGetSetDetails methods */
void   cloud__resp_get_set_details__init
                     (Cloud__RespGetSetDetails         *message);
size_t cloud__resp_get_set_details__get_packed_size
                     (const Cloud__RespGetSetDetails   *message);
size_t cloud__resp_get_set_details__pack
                     (const Cloud__RespGetSetDetails   *message,
                      uint8_t             *out);
size_t cloud__resp_get_set_details__pack_to_buffer
                     (const Cloud__RespGetSetDetails   *message,
                      ProtobufCBuffer     *buffer);
Cloud__RespGetSetDetails *
       cloud__resp_get_set_details__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cloud__resp_get_set_details__free_unpacked
                     (Cloud__RespGetSetDetails *message,
                      ProtobufCAllocator *allocator);
/* Cloud__CloudConfigPayload methods */
void   cloud__cloud_config_payload__init
                     (Cloud__CloudConfigPayload         *message);
size_t cloud__cloud_config_payload__get_packed_size
                     (const Cloud__CloudConfigPayload   *message);
size_t cloud__cloud_config_payload__pack
                     (const Cloud__CloudConfigPayload   *message,
                      uint8_t             *out);
size_t cloud__cloud_config_payload__pack_to_buffer
                     (const Cloud__CloudConfigPayload   *message,
                      ProtobufCBuffer     *buffer);
Cloud__CloudConfigPayload *
       cloud__cloud_config_payload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cloud__cloud_config_payload__free_unpacked
                     (Cloud__CloudConfigPayload *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Cloud__CmdGetSetDetails_Closure)
                 (const Cloud__CmdGetSetDetails *message,
                  void *closure_data);
typedef void (*Cloud__RespGetSetDetails_Closure)
                 (const Cloud__RespGetSetDetails *message,
                  void *closure_data);
typedef void (*Cloud__CloudConfigPayload_Closure)
                 (const Cloud__CloudConfigPayload *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    cloud__cloud_config_status__descriptor;
extern const ProtobufCEnumDescriptor    cloud__cloud_config_msg_type__descriptor;
extern const ProtobufCMessageDescriptor cloud__cmd_get_set_details__descriptor;
extern const ProtobufCMessageDescriptor cloud__resp_get_set_details__descriptor;
extern const ProtobufCMessageDescriptor cloud__cloud_config_payload__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_cloud_2eproto__INCLUDED */
