COMPONENT_SRCDIRS := src
COMPONENT_ADD_INCLUDEDIRS := include
COMPONENT_PRIV_INCLUDEDIRS := src

COMPONENT_SRCDIRS += utils/src
COMPONENT_ADD_INCLUDEDIRS += utils/include

COMPONENT_SRCDIRS += platforms/aws
COMPONENT_PRIV_INCLUDEDIRS += platforms/include
